"""``sobai aliases install`` — generate safe shell wrappers.

The wrappers are thin functions that forward their arguments to the canonical
``sobai`` command using ``"$@"`` / ``$argv``. They never use ``eval`` and never
build a command string, so there is no word-splitting or injection surface. The
canonical interface is always ``sobai``; these are conveniences, not a second
implementation.
"""

from __future__ import annotations

from typing import Annotated

import typer

from sobai.core.errors import ConfigError

from .common import get_ctx

# name -> (fixed sobai subcommand, use_separator).
# use_separator=True inserts `--` before the forwarded args so a natural-language
# prompt beginning with `-` is never parsed as an option. Wrappers that forward
# *options* (e.g. sobai-update --check) set it False so options pass through.
_WRAPPERS: dict[str, tuple[list[str], bool]] = {
    "yb-claude": (["youtube", "ask", "--provider", "claude"], True),
    "yb-cx": (["youtube", "ask", "--provider", "openai"], True),
    "notion-claude": (["notion", "ask", "--provider", "claude"], True),
    "notion-cx": (["notion", "ask", "--provider", "openai"], True),
    "sobai-update": (["update"], False),
}

_SUPPORTED = ("bash", "zsh", "fish")

_HEADER = (
    "# >>> SoBatista AI shell wrappers >>>\n"
    "# Generated by `sobai aliases install`. Arguments are forwarded verbatim;\n"
    "# no shell interpretation of arguments is performed.\n"
)
_FOOTER = "# <<< SoBatista AI shell wrappers <<<\n"

aliases_app = typer.Typer(help="Install safe shell wrappers for common workflows.")


def _render(shell: str) -> str:
    lines = [_HEADER]
    for name, (argv, sep) in _WRAPPERS.items():
        args = " ".join(argv)
        if shell == "fish":
            forward = f"{args} -- $argv" if sep else f"{args} $argv"
            lines.append(f"function {name}\n    command sobai {forward}\nend\n")
        else:  # bash / zsh share POSIX function syntax
            forward = f'{args} -- "$@"' if sep else f'{args} "$@"'
            lines.append(f"{name}() {{\n    command sobai {forward}\n}}\n")
    lines.append(_FOOTER)
    return "\n".join(lines)


@aliases_app.command("install")
def aliases_install(
    ctx: typer.Context,
    shell: Annotated[str, typer.Argument(help="Shell: bash, zsh, or fish.")],
    print_only: Annotated[
        bool, typer.Option("--print", help="Print the wrappers instead of writing a file.")
    ] = False,
) -> None:
    """Generate wrappers (yb-claude, yb-cx, notion-claude, notion-cx, sobai-update)."""
    app = get_ctx(ctx)
    shell = shell.lower()
    if shell not in _SUPPORTED:
        raise ConfigError(
            f"Unsupported shell '{shell}'.",
            hint=f"Supported: {', '.join(_SUPPORTED)}.",
        )
    content = _render(shell)

    if print_only:
        # Print raw so it can be piped/redirected; bypasses Rich styling.
        print(content)
        return

    app.paths.ensure()
    ext = "fish" if shell == "fish" else shell
    target = app.paths.config_dir / f"aliases.{ext}"
    target.write_text(content, encoding="utf-8")
    if shell == "fish":
        source_line = f"source {target}"
        rc = "~/.config/fish/config.fish"
    else:
        source_line = f"source {target}"
        rc = f"~/.{shell}rc"
    app.ui.success(f"Wrote wrappers to {target}")
    app.ui.print(f"Add this line to [heading]{rc}[/heading] to enable them:")
    app.ui.print(f"  [info]{source_line}[/info]")
    app.ui.print("[muted]Then restart your shell or `source` the file.[/muted]")
